### ISSUE TITLE
Allow two way Audio with Foscam IP Camera

### ISSUE THREAD

**Issue by confile** [bobbyromeo/mypihc#2]
This is a really great project. I read that the Foscam IP Camera has two way audio. Is it possible to extend your project by: 
1. Getting the audio from the cameras?
2. Sending audio to the speaker of the cameras?

Happy to discuss this with you.

**Comment by drmichaelgorski** [comment]
Also moving the camera would be great.

**Comment by joelones** [comment]
Added pan/tilt (left,right,up,down) for Foscam cameras.

**Comment by bobbyromeo** [comment]
Added pan/tilt (left,right,up,down) for foscam cameras.
